name: Build & deploy Mobile

on:
  push:
    branches:
      - main
    paths:
      - "apps/mobile/**"
      - "packages/shared-core/**"
      - "packages/shared-dto/**"

  workflow_dispatch:

jobs:
  build:
    name: Build & deploy Mobile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Hello World Action
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mobile App'
